### ISSUE TITLE
Palette colors should be availble to use in display declarations in config.design-tokens.yml

### ISSUE THREAD

**Issue by coreylafferty** [forumone/gesso#232]
Currently under the 'display' section of the config.design-tokens.yml file you can reference colors from the color section of the same file.  Example:

```
display:
  h1:
    font-family: primary.stack
    font-weight: bold
    font-size: 6
    color: text.primary
```

However, this only works with colors from the 'color' section.  The following will NOT work (but should):

```
display:
  h1:
    font-family: primary.stack
    font-weight: bold
    font-size: 6
    color: palette.brand.blue
```

Not sure whether this should involve a change where colors under display referenced by the full paths (e.g., colors.text.primary and palette.brand.blue) or whether it should assume the first prefix (e.g., text.primary and brand.blue). In the latter case I suspect it'd be possible for there to be conflicts in theory. 

Notes:
- Branch off of branch 8.x-3.x-config for this issue
- To get things running, follow instructions in Readme (short version:  npm install, then gulp)
- See function getScalarVisitor in file /lib/transform.js for where the Display settings are read/transformed
