### ISSUE TITLE
Change breakpoint token names

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#305]
I don’t typically use the default breakpoint design tokens on a project, but rather create new ones with names that describe what it is for (e.g., breadcrumbs, font-size, etc.)

The current breakpoint design tokens use shorthand for sizes (e.g., xs, sm, md, lg) and it’s not clear to me what those tokens represent. How do folks feel about switching to the USWDS naming convention for breakpoint tokens?

Current:
```
breakpoints:
  xs: 480px
  sm: 700px
  md: 960px
  lg: 1280px
```

Proposed:
```
breakpoints:
  mobile: 320px
  mobile-lg: 480px
  tablet: 640px
  tablet-lg: 880px
  desktop: 1024px
  desktop-lg: 1200px
  widescreen: 1400px
```
