### ISSUE TITLE
Add disabled border token

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#340]
As suggested in #335:

```
disabled:
  background: grayscale.gray-2
  border: grayscale.gray-4
  text: grayscale.gray-4
```
